### ISSUE TITLE
Switch does go back on again, when switching off via Home Assistant GUI

### ISSUE THREAD

**Issue by hajo62** [FreshlyBrewedCode/hacs-homee#10]
Haven't found a thread in the Home Assistant community; therefore I ask here.

I have imported my devices from Homee to Home Assistant and - not sure - but I think my Fibaro wall plug switch worked well at the beginning. Now, after about one day, I can't swich on (or off) from Home Assistant. When I toggle the switch - i.e. switch off - it is switched on again after a view seconds. 
When I switch off in the Homee web ui, it works well.
After I restarted Home Assistant, it worked again well, but again only for a while.

How would I debug what causes this behavior?

**Comment by FreshlyBrewedCode** [comment]
This happens commonly if HA has lost the connection to homee or homee takes to long to respond. Once you toggle the switch a command should be dispatched to homee but the switch will return to the actual state of the HA entity after a few seconds. So if homee does not update and report the new state back to HA the switch will flip back on/off to the last known state.

I will need some additional information:
- Does the Fibaro plug actually turn off despite the UI not updating correctly?
- Are there any errors in your HA logs?
- What is the debug information of the Fibaro plug entity? (toggle "Add debug information" in the configuration and click on the entity)

Restarting HA will reload the integration and perform a fresh reconnect to homee which fixes any previous connection problems.

**Comment by hajo62** [comment]
Thanks for your fast response.
Haven't seen a log entry.
I will check when it occurs the next time.

**Comment by hajo62** [comment]
It happened again.

- Does the Fibaro plug actually turn off despite the UI not updating correctly?
No, it does not change it's state

- Are there any errors in your HA logs?
```
2021-07-15 08:49:04 ERROR (MainThread) [frontend.js.latest.202106030] https://ha.hajo62.duckdns.org/lovelace/repeater?edit=1:0:0 Uncaught
2021-07-15 08:49:31 ERROR (MainThread) [frontend.js.latest.202106030] https://ha.hajo62.duckdns.org/hacsfiles/lovelace-weather-card-chart/weather-card-chart.js?hacstag=163941792028:563:22 NotSupportedError: Cannot define multiple custom elements with the same tag name
2021-07-15 08:50:08 ERROR (MainThread) [frontend.js.latest.202106030] https://ha.hajo62.duckdns.org/lovelace/repeater?edit=1:0:0 Uncaught
2021-07-15 08:58:10 ERROR (MainThread) [frontend.js.latest.202106030] https://ha.hajo62.duckdns.org/lovelace/repeater:0:0 Uncaught 
```

Regarding the debug info: I missed to set the switch. Just set it now and that's what I see on Developer Tools / Entities / Attributes:
```
current_power_w: 0
today_energy_kwh: 0.07
homee_data: 
id: 11
name: FIBARO Repeater
profile: 13
attributes:
  - id: 100
    type: 1
  - id: 101
    type: 44
  - id: 102
    type: 45
  - id: 103
    type: 4
  - id: 104
    type: 47
  - id: 105
    type: 48
  - id: 106
    type: 3
  - id: 107
    type: 347

friendly_name: FIBARO Repeater
device_class: outlet
```
Not sure if set helps. Will do a HA restart and look if the next failure will show more info in the attributes. Or would I see the debug info?

**Comment by FreshlyBrewedCode** [comment]
Thanks for the info. At first glance, it looks like the integration is just losing the connection to homee. You could try to verify this by checking if you get the same behavior for other devices or if the problem only occurs for the Fibaro plug. 
Although very unlikely, it could also be a problem between homee and the plug. You could verify this by toggling the plug from the homee UI and check if it actually switches and if the HA UI updates as well.

If it is "just" a connection problem there is unfortunately very little I can do to help. I am struggling with occasional disconnects myself and the integration *should* try to reconnect after it lost the connection to homee but sometimes restarting HA is the only way to restore the connection.

**Comment by hajo62** [comment]
Hi,

* Same behavior for other device: **Yes**
* Toggling the plug from the homee UI: **That works well** as well as the state change is shown in HA, too.

**Comment by FreshlyBrewedCode** [comment]
> **That works well** as well as the state change is shown in HA

This is strange. This may suggest that there is a problem with the service that is used to send new values to homee. Do you have more than one homee configured in HA?

You can also try to manually call the service next time the issue occurs by going to the services section of the HA developer tools and calling the `homee.set_value` service with the following data:
```yaml
node: 11
attribute: 100
value: 0    # 0 for off, 1 for on
```

**Comment by hajo62** [comment]
Just one homee.

Like this?
<img width="252" alt="grafik" src="https://user-images.githubusercontent.com/15800980/126050998-831678d3-a101-4d38-8d5e-9ff536ca8711.png">
 Looks liek it does not work, too.

**Comment by Gaili** [comment]
Same problem with my HA and Homee

**Comment by FreshlyBrewedCode** [comment]
As mentioned on the forum, you could try to reload the integration to force it to reconnect:
![image](https://user-images.githubusercontent.com/11772241/129951313-dc491bb4-fb8b-406e-b37d-010764d4ee9f.png)
This could even be automated using the `reload_config_entry` [service](https://www.home-assistant.io/integrations/homeassistant/#service-homeassistantreload_config_entry), however, I have not tried it yet.

**Comment by Gaili** [comment]
Yeah it`s working with reload, meanwhile i have a workaround with mqqt.
greets

**Comment by hajo62** [comment]
I'll close the issue.
Looks like it works - although I haven't changed something except the HA version to 2021.11.4
