### ISSUE TITLE
Reloading the 1.5.0 integration disables all Homee entities in Homeassistant. HA needs restart to get them re-enabled. 

### ISSUE THREAD

**Issue by mesistostefre** [FreshlyBrewedCode/hacs-homee#15]
Reloading the 1.5.0 integration disables all Homee entities in Homeassistant. HA needs restart to get them re-enabled. 

Homee integration 1.5.0
HA Core 2022.10.2
HA Supervisor 2022.10.0

## Type of problem
- [x] I found a bug 

## Version
1.5.0

## Detailed description
- a)
- go to Configuration/Integration
- reload Homee 1.5.0 integration
- => all existing homee entities will be disabled
- b)
- Workaround: Restart HA 
- => Homee entities are re-enabled.

**Comment by FreshlyBrewedCode** [comment]
Could it be that the Homee integration does not reload properly? Could you check if e.g. the `homee.set_value` service is available after the reload?

**Comment by mesistostefre** [comment]
Sorry, was on the road… yes, service is available after reload and I can execute it.

What I did: developes tab/services/ : select “home: set_value” and enter “value: 42” to be the service data. When I execute the call, I get the green check mark in return.
Still, all  entities are disabled.


Von: Karl Möller ***@***.***>
Datum: Montag, 10. Oktober 2022 um 19:08
An: FreshlyBrewedCode/hacs-homee ***@***.***>
Cc: mesistostefre ***@***.***>, Author ***@***.***>
Betreff: Re: [FreshlyBrewedCode/hacs-homee] Reloading the 1.5.0 integration disables all Homee entities in Homeassistant. HA needs restart to get them re-enabled. (Issue #15)

Could it be that the Homee integration does not reload properly? Could you check if e.g. the homee.set_value service is available after the reload?

**Comment by mesistostefre** [comment]
But I do see an entry in the logs which I must have overlooked before.
The entry is not because of me executing the service, but instead gets created when I trigger the reload of the integration:

“Error unloading entry homee @ (xxx.xxx.xxx.xx) for climate
19:15:55 – (FEHLER) helpers/entity_component.py – “

The details are:
“
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:175
First occurred: 19:04:04 (7 occurrences)
Last logged: 19:15:55

  *   Error unloading entry homee @ (xxx.xxx.xxx.xx) for climate
  *   Error unloading entry homee @ (xxx.xxx.xxx.xx) for binary_sensor
  *   Error unloading entry homee @ (xxx.xxx.xxx.xx) for switch
  *   Error unloading entry homee @ (xxx.xxx.xxx.xx) for cover
  *   Error unloading entry homee @ (xxx.xxx.xxx.xx) for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 498, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 262, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 175, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
”

PS: xxx.xxx.xxx.xx is the IP address of homee

Von: Karl Möller ***@***.***>
Datum: Montag, 10. Oktober 2022 um 19:08
An: FreshlyBrewedCode/hacs-homee ***@***.***>
Cc: mesistostefre ***@***.***>, Author ***@***.***>
Betreff: Re: [FreshlyBrewedCode/hacs-homee] Reloading the 1.5.0 integration disables all Homee entities in Homeassistant. HA needs restart to get them re-enabled. (Issue #15)

Could it be that the Homee integration does not reload properly? Could you check if e.g. the homee.set_value service is available after the reload?

**Comment by Stklingner** [comment]
It could be due to the new device implementation - will take a look this weekend

**Comment by Stklingner** [comment]
@mesistostefre - this has been patched in now; would you try it again when you get the chance, please?

**Comment by mesistostefre** [comment]
Congratulations: you fixed it! 

Upgraded to 2.0.1, reloading the integration works as well.
A few sensors, switches,  and lights got lost, but re-appeared under a new name, basically with an "_2" attached.n
Other switches and lights just survived.
So, after adjusting the automations to use the new entities, all is nice and well.

Thanks again, great job!

Problem I have now: I do not see how i can drop you a treat ... or at least a coffee... :-(

**Comment by FreshlyBrewedCode** [comment]
Closed by #17, Fixed in 2.0.0
