### ISSUE TITLE
Unable to prepare setup for platform homee.sensor: Platform not found (No module named 'custom_components.homee.sensor')

### ISSUE THREAD

**Issue by HennigMatthias** [FreshlyBrewedCode/hacs-homee#16]
Unable to prepare setup for platform homee.sensor: Platform not found (No module named 'custom_components.homee.sensor')

Checked the custom_components folder. There is no /custom_components/homee.sensor file.

Version v1.5.0

Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.2

**Comment by FreshlyBrewedCode** [comment]
Oh you are right, this slipped in with the last PR. @Stklingner was working on the sensor platform but it is not implemented yet.
