### ISSUE TITLE
Expose homee status

### ISSUE THREAD

**Issue by hajo62** [FreshlyBrewedCode/hacs-homee#21]
As far as I understand, the integration exposes _only_ sensor values from devices.

I would like to have the option, to see **and** update the homee status value reflecting if at home or sleeping or ...
<img width="465" alt="image" src="https://user-images.githubusercontent.com/15800980/204556401-eef18b49-5e4e-4c40-9303-02f097546e31.png">

**Comment by FreshlyBrewedCode** [comment]
I won't be adding any new features. I am just passively maintaining the project. But PRs are always welcome.

**Comment by Taraman17** [comment]
First test shows, that the change is reported to HA, so it should be possible to have a sensor for that.

**Comment by FreshlyBrewedCode** [comment]
see https://github.com/Taraman17/hacs-homee/issues/6
