### ISSUE TITLE
Impulse type switches not discovered

### ISSUE THREAD

**Issue by Taraman17** [FreshlyBrewedCode/hacs-homee#23]
## Type of problem
- [ ] A feature does not work as expected.

## Version
2.0.2

## Detailed description
I added my Homee (Hörmann Homee Cube).
It has 2 devices:
- 1 Garage door cover
- 1 Switch actuating my yard gate

These are in 1 Group ("Tore"). The group is sucessfully discovered, but if I add it, only the homee cube itself is discovered.
On the first try, the Garage door was found, but after deleting and reinitialisizing, both devices are not discovered.

edit: The garage door is only found after the area is set for the homee base.

The Log does not show any errors.

## Error log
```text
2023-02-15 14:46:29.558 INFO (MainThread) [custom_components.homee.config_flow] got access token for homee
2023-02-15 14:46:29.559 INFO (MainThread) [custom_components.homee.config_flow] homee task created
2023-02-15 14:46:29.698 INFO (MainThread) [custom_components.homee.config_flow] homee connected
2023-02-15 14:46:29.699 INFO (MainThread) [custom_components.homee.config_flow] homee disconnecting
2023-02-15 14:46:29.722 INFO (MainThread) [custom_components.homee.config_flow] homee config successfully tested
2023-02-15 14:46:29.723 INFO (MainThread) [custom_components.homee.config_flow] created new homee entry with ID 00055112EACA
```

**Comment by Taraman17** [comment]
With a line of log code added, I could confirm that the node is found, but not added in the UI:

```
2023-02-16 08:44:54.321 INFO (MainThread) [custom_components.homee.config_flow] got access token for homee
2023-02-16 08:44:54.322 INFO (MainThread) [custom_components.homee.config_flow] homee task created
2023-02-16 08:44:54.465 INFO (MainThread) [custom_components.homee.config_flow] homee connected
2023-02-16 08:44:54.465 INFO (MainThread) [custom_components.homee.config_flow] homee disconnecting
2023-02-16 08:44:54.501 INFO (MainThread) [custom_components.homee.config_flow] homee config successfully tested
2023-02-16 08:44:54.502 INFO (MainThread) [custom_components.homee.config_flow] created new homee entry with ID XXXXXXXXX
2023-02-16 08:44:57.963 INFO (MainThread) [custom_components.homee.helpers] node foundGaragentor
2023-02-16 08:44:57.963 INFO (MainThread) [custom_components.homee.helpers] node foundHoftor
2023-02-16 08:44:57.963 INFO (MainThread) [custom_components.homee.helpers] node foundGaragentor
2023-02-16 08:44:57.964 INFO (MainThread) [custom_components.homee.helpers] node foundHoftor
2023-02-16 08:44:57.964 INFO (MainThread) [custom_components.homee.helpers] node foundGaragentor
2023-02-16 08:44:57.964 INFO (MainThread) [custom_components.homee.helpers] node foundHoftor
2023-02-16 08:44:57.965 INFO (MainThread) [custom_components.homee.helpers] node foundGaragentor
2023-02-16 08:44:57.965 INFO (MainThread) [custom_components.homee.helpers] node foundHoftor
2023-02-16 08:44:57.965 INFO (MainThread) [custom_components.homee.helpers] node foundGaragentor
2023-02-16 08:44:57.966 INFO (MainThread) [custom_components.homee.helpers] node foundHoftor
2023-02-16 08:44:57.966 INFO (MainThread) [custom_components.homee.helpers] node foundGaragentor
2023-02-16 08:44:57.966 INFO (MainThread) [custom_components.homee.helpers] node foundHoftor
```

**Comment by Taraman17** [comment]
Today I decided to have a closer look into the code and found the causes for my problem.

The yard gate is controlled by a radio-relay which is of  type IMPULSE_RELAY (Protocol 43) which is not yet configured as switch. Also it does not have the Attribute Type ON_OFF (1), but WatchdogOnOff (385) [1].

At this point my efforts stalled, beacuse I could use some help setting up the Devcontainer. I have the ha-core running fine, but don't know how to properly integrate this component for development. So far I just copied the files manually into the HA devcontainer, but now I don't know where the pymee files reside, which need to be changed also.

If I could get some hints on this, I should be able to add proper support for my two devices.

[1]: https://github.com/stfnhmplr/homee-api/blob/main/lib/enums.js

**Comment by Stklingner** [comment]
@Taraman17 if you copy the repo files into vscode under custom_components/hacs-homee and then rebuild the container it should work IIRC

**Comment by Stklingner** [comment]
Let me know how you get on - there are a few things I'd like to have a look at and I can add this to the list

**Comment by Taraman17** [comment]
> @Taraman17 if you copy the repo files into vscode under custom_components/hacs-homee and then rebuild the container it should work IIRC

So that is copy the pymee files to a directory "vscode" in the custom_components/hacs-homee dir, or do you mean I copy them using vscode to the hacs-homee directory?

**Comment by Stklingner** [comment]
> So that is copy the pymee files to a directory "vscode" in the custom_components/hacs-homee dir, or do you mean I copy them using vscode to the hacs-homee directory?

Sorry, half asleep today - copy the "homee" folder in "custom_components" 
from hacs-homee into a folder called "custom_components" in the core repository using vscode (you can just drag the folder from your explorer/finder into vscode's file list on the sidebar), then rebuild the container and it will install the dependencies.

**Comment by Taraman17** [comment]
I got so far, but now I need to change files in the pymee library.
How do I achieve that?

**Comment by Stklingner** [comment]
> I got so far, but now I need to change files in the pymee library.
> 
> How do I achieve that?

Nice job so far! So now we need to take a modified version of pymee that you’re going to be playing around with:

1. Fork freshlybrewed’s pymee repo to your account
2. open the terminal in your dev environment in vscode (down the bottom)
3. Now you should be able to do pip uninstall pymee and then pip install git+https://<your repo>@<whichever branch you want>
4. Modify your pymee code in another window, commit back to GitHub then reinstall as per 3 to try out (if in doubt, rebuild the container)
5. Rinse and repeat

You used to be able to change the manifest requirement to a GitHub reference and use the “install all dependencies” command in the dev environment but this broke a while back…

**Comment by Taraman17** [comment]
Great, thank you. Try that as soon as I have time.

**Comment by Taraman17** [comment]
Ok, succeded in running the commands, but when I start Homeassistant in the DevContainer, pymee gets overwritten with the original version.

**Comment by Taraman17** [comment]
First progress is made - I can discover the devices as switches and have the position sensor for the garage door.
When I try to use the switches however I get errors.

It tries to change the attribute "21" to "1" to turn the switch to on.
But the garage door uses Attribute 22 as switch:
```
[
{'id': 21, 'node_id': 3, 'instance': 0, 'minimum': 0, 'maximum': 1, 'current_value': 0.0, 'target_value': 0.0, 'last_value': 1.0, 'unit': '', ...}
{'id': 22, 'node_id': 3, 'instance': 0, 'minimum': 0, 'maximum': 1, 'current_value': 0.0, 'target_value': 0.0, 'last_value': 0.0, 'unit': 'n%2Fa', ...},
{'id': 23, 'node_id': 3, 'instance': 0, 'minimum': 0, 'maximum': 100, 'current_value': 100.0, 'target_value': 100.0, 'last_value': 100.0, 'unit': '%25', ...},
{'id': 24, 'node_id': 3, 'instance': 0, 'minimum': 0, 'maximum': 4, 'current_value': 1.0, 'target_value': 1.0, 'last_value': 1.0, 'unit': 'n%2Fa', ...},
{'id': 25, 'node_id': 3, 'instance': 0, 'minimum': 0, 'maximum': 1, 'current_value': 0.0, 'target_value': 0.0, 'last_value': 0.0, 'unit': 'n%2Fa', ...},
{'id': 26, 'node_id': 3, 'instance': 0, 'minimum': 0, 'maximum': 30, 'current_value': 5.0, 'target_value': 5.0, 'last_value': 0.0, 'unit': 'min', ...}
]
```
Attribute 21 here is showing if the impulse is active i beleive, but could not confirm that.
It should also have another impulse switch for the light, if configured.

The relay for the yard gate has two switches:
```
[
{'id': 27, 'node_id': 9, 'instance': 0, 'minimum': 0, 'maximum': 1, 'current_value': 1.0, 'target_value': 1.0, 'last_value': 0.0, 'unit': '', ...},
{'id': 28, 'node_id': 9, 'instance': 1, 'minimum': 0, 'maximum': 1, 'current_value': 0.0, 'target_value': 0.0, 'last_value': 0.0, 'unit': 'n%2Fa', ...},
{'id': 29, 'node_id': 9, 'instance': 2, 'minimum': 0, 'maximum': 1, 'current_value': 0.0, 'target_value': 0.0, 'last_value': 0.0, 'unit': 'n%2Fa', ...},
{'id': 30, 'node_id': 9, 'instance': 0, 'minimum': 0, 'maximum': 30, 'current_value': 5.0, 'target_value': 5.0, 'last_value': 0.0, 'unit': 'min', ...}
]
```
Attributes 28 & 29. As far as I know, it supports up to 4 different impulses that can be sent through the original remote.

So next I have to figure out how to call to different Attributes for switching.

**Comment by Taraman17** [comment]
Research showed that this might be related to the debugging environment, so today as the updated pymee lib was available I tested on my production HA and there it works. ;-)

**Comment by Pr0mises** [comment]
@Taraman17 are you also able to control your Garagentor with hass? I only get a status and the position slider which does nothing.

**Comment by Taraman17** [comment]
@Pr0mises after the update I get the Garagedoor as a switch and a sensor.
Before there was the slider which did not work, since the opener only accepts impulses to start/stop and not position commands.

Yesterday on testing it worked well - this morning it doesn't. Need to find out why.

**Comment by Pr0mises** [comment]
@Taraman17 did you mean it reverted back to the slider?
The update didn't do anything to my garagedoor. I'll try to purge homee from hass and connect it again if it changed for you

**Comment by Taraman17** [comment]
I noticed that the slider is still present.
I need to also change cover.py so that it does not reacts on impulse operators

**Comment by Taraman17** [comment]
@Stklingner follow up question:
Is there a way to get the logs from the pymee library out of the DevContainer?
I saw it logs quite a lot of interesting stuff.

**Comment by Stklingner** [comment]
@Taraman17 As you've surmised, they should be somewhere in the container but I'm not sure where to begin - the structure is explorable via the vscode terminal so should be findable! 

I only used python scripts when dealing with pymee; I find that there's so much going on in HA it's difficult to really see what it's doing...

**Comment by Taraman17** [comment]
@Stklingner Thx, I figured out, that if I put logging to debug, I see it in the HA Logs via the UI.

**Comment by serdar-22** [comment]
hello

since the update i have the issue, that only sometimes can open the garage door.

i have to click at least 5-6 times, that sometimes garage door will open.
 i dont found any errors in the log.

thank you very much for your support

**Comment by serdar-22** [comment]
sorry after restart its ok 👍🏾

**Comment by Pr0mises** [comment]
v2.3 is working for me. Good job !

**Comment by spainpiio** [comment]
All of a sudden, all of my dimmer switches have disappeared and are shown as unavailable.
The sensors of these dimmers, however, are available.
They are Fibaro & Qubino dimmers that work directly in Homee.
I have already deleted the integration and reinstalled, restarted....
Does anyone have any ideas?

**Comment by Taraman17** [comment]
Can you set the logging to info and post the logs from HACS-homee?

**Comment by spainpiio** [comment]
Logger: homeassistant.components.light
Source: custom_components/homee/light.py:42
Integration: Licht (documentation, issues)
First occurred: 08:52:43 (1 occurrences)
Last logged: 08:52:43

Error while setting up homee platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/homee/light.py", line 107, in async_setup_entry
    devices.append(HomeeLight(node, light_set, index, config_entry))
  File "/config/custom_components/homee/light.py", line 153, in __init__
    self._supported_features = get_light_features(self)
  File "/config/custom_components/homee/light.py", line 42, in get_light_features
    features |= ColorMode.BRIGHTNESS  #
TypeError: unsupported operand type(s) for |=: 'int' and 'ColorMode'

and

Logger: homeassistant.helpers.service
Source: helpers/service.py:645
First occurred: 08:52:44 (4 occurrences)
Last logged: 09:42:59

Unable to find referenced entities light.pb_oficina_luz or it is/they are currently not available

**Comment by Taraman17** [comment]
Thx, should be fixed

**Comment by Taraman17** [comment]
Fixed with https://github.com/FreshlyBrewedCode/hacs-homee/pull/32
