### ISSUE TITLE
Support sensor component

### ISSUE THREAD

**Issue by FreshlyBrewedCode** [FreshlyBrewedCode/hacs-homee#3]
**Is your feature request related to a problem? Please describe.**
Numerical sensors like temperature, humidity, motion or light sensors are currently not supported. 

**Describe the solution you'd like**
Implement the homee platform for the Home Assistant [sensor component](https://www.home-assistant.io/integrations/sensor/).

**Describe alternatives you've considered**

**Additional context**
Possible related [homee node profiles](https://github.com/FreshlyBrewedCode/pymee/blob/370006b58fb7a793ba130b8f5998b6c941c41bba/pymee/const.py#L1):
see https://github.com/stfnhmplr/homebridge-homee/blob/master/lib/node_types.js

Possible related [attribute types](https://github.com/FreshlyBrewedCode/pymee/blob/370006b58fb7a793ba130b8f5998b6c941c41bba/pymee/const.py#L174):
see https://github.com/stfnhmplr/homebridge-homee/blob/master/lib/attribute_types.js

- Additional device properties such as battery level could be implemented using the sensor component

**Comment by Stklingner** [comment]
Will get this done this weekend :)
