### ISSUE TITLE
hacs-homee does not work at all in the latest home assistant

### ISSUE THREAD

**Issue by godza** [FreshlyBrewedCode/hacs-homee#33]
## Type of problem
- [ ] A feature does not work as expected.
- [ ] I found a bug (see the error log below).

## Version
hacs-homee 2.3.2
home-asisstant 2023.4.2

## Detailed description
During the initialization of the home assistant, there is an error regarding homee initialization

## Error log
```
Logger: homeassistant.setup
Source: setup.py:205 
First occurred: 8:59:22 PM (1 occurrences) 
Last logged: 8:59:22 PM

Setup failed for custom integration homee: Requirements for homee not found: ['websockets==10.3'].
```
error in the log before this one is probably related
```
Logger: homeassistant.util.package
Source: util/package.py:107 
First occurred: 8:59:19 PM (3 occurrences) 
Last logged: 8:59:22 PM

Unable to install package websockets==10.3: ERROR: Cannot install websockets==10.3 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
```

**Comment by Grafzahl2379** [comment]
Hello

I have the Problem here.

**Comment by Gulaschkanone88** [comment]
Me to

**Comment by kthofmann** [comment]
I had the same problem, reverted to home-asisstant 2023.4.1

**Comment by r4nt** [comment]
Applying the patch above works for me, I've not found any problems with the newer websockets version so far.

**Comment by Pr0mises** [comment]
> Applying the patch above works for me, I've not found any problems with the newer websockets version so far.

thank you, fixed for me no problems so far besides of existing ones
