### ISSUE TITLE
Entities disappeared after upgrading HomeAssistant to 2023.9

### ISSUE THREAD

**Issue by ikrentchev** [FreshlyBrewedCode/hacs-homee#45]
## Type of problem

- [ ] I have a question.
- [ ] A feature does not work as expected.
- [X ] I found a bug (see error log below).

## Version
 2.5.0

## Detailed description
A clear and concise description of the question/problem/bug
After upgrading HomeAssistant to 2023.9 homee lost all its entities. After clear re-install for both homee device and homee integration, I still got no entities under the homee device. I have done this several times in the past but this time it is different.

## Error log

```text

Add your logs here.

```

**Comment by Taraman17** [comment]
This will be issue #42, which is about to be fixed - Pull request is awaiting review.
You will find the respective error messages in the log.
