### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Taraman17** [FreshlyBrewedCode/hacs-homee#46]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
translate the strings in Homee Integration to German.

**Describe alternatives you've considered**
None - really.

**Additional context**
As Homee is a product that is used in Germany a lot, I think it would be a good thing to a have a german translation

**Comment by FreshlyBrewedCode** [comment]
see https://github.com/Taraman17/hacs-homee/issues/10
