### ISSUE TITLE
Option to import all devices regardless of their groups

### ISSUE THREAD

**Issue by FreshlyBrewedCode** [FreshlyBrewedCode/hacs-homee#5]
**Is your feature request related to a problem? Please describe.**
A new option introduced in v1.2.0 allows the user to select which groups should be imported. The integration will only import devices that are in any of the selected groups. This behaviour will cause devices that are not assigned to a group to never be imported.

**Describe the solution you'd like**
Add an option to import all devices regardless of what groups are selected.

**Describe alternatives you've considered**
Move all devices to at least one group.

**Additional context**
The option should be added to the `get_data_schema` function in `config_flow.py` and `get_imported_nodes` in `helpers.py` should return all nodes if the option is enabled.

**Comment by Taraman17** [comment]
I'm currently working on this one.

I wonder if there is a chance to get rid of the Door / Window Sensor group setting.
Don't these devices have a Device Profile or anything that lets us recognize them?

Maybe anyone using those with homee reading this can send us a log to check.

**Comment by FreshlyBrewedCode** [comment]
see https://github.com/Taraman17/hacs-homee/issues/3
