### ISSUE TITLE
Rollershutter

### ISSUE THREAD

**Issue by jhpaulsen** [FreshlyBrewedCode/hacs-homee#6]
**Is your feature request related to a problem? Please describe.**
So far some devices already work great. Including more device profiles such as Roller shutters Would be great

**Describe the solution you'd like**
Inclusion of new devices or

**Describe alternatives you've considered**
A description how others could help/ assist in doing so. „How to add device profiles“ so that other users could test and create pull requests

**Comment by FreshlyBrewedCode** [comment]
Closing, because the feature is already addressed in #2

**Comment by FreshlyBrewedCode** [comment]
> A description how others could help/ assist in doing so. „How to add device profiles“ so that other users could test and create pull requests

Currently certain devices require the implementation of new components (e.g. cover, sensor, etc.). This is related to the (Home Assistant architecture)[https://developers.home-assistant.io/docs/architecture_components] and is sadly not as simple as adding new profiles to a list.
